// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjRRZJDrAA5WHzkFYIwYais0S-5NQ0pOk',
    appId: '1:538338843:web:08b9b779d3ff14c04fbabe',
    messagingSenderId: '538338843',
    projectId: 'study-app-43ddd',
    authDomain: 'study-app-43ddd.firebaseapp.com',
    storageBucket: 'study-app-43ddd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5IiVRPYbtn5_SNzcxT61onYZ9BRqNsVM',
    appId: '1:538338843:android:d7a7f6ba7dd12d844fbabe',
    messagingSenderId: '538338843',
    projectId: 'study-app-43ddd',
    storageBucket: 'study-app-43ddd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV39z0SBaHbl7a3WFav-zXF0TYb959Ii8',
    appId: '1:538338843:ios:313870496cff26e54fbabe',
    messagingSenderId: '538338843',
    projectId: 'study-app-43ddd',
    storageBucket: 'study-app-43ddd.firebasestorage.app',
    iosBundleId: 'com.example.flutterStudyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV39z0SBaHbl7a3WFav-zXF0TYb959Ii8',
    appId: '1:538338843:ios:313870496cff26e54fbabe',
    messagingSenderId: '538338843',
    projectId: 'study-app-43ddd',
    storageBucket: 'study-app-43ddd.firebasestorage.app',
    iosBundleId: 'com.example.flutterStudyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjRRZJDrAA5WHzkFYIwYais0S-5NQ0pOk',
    appId: '1:538338843:web:3d80e397e4bf71774fbabe',
    messagingSenderId: '538338843',
    projectId: 'study-app-43ddd',
    authDomain: 'study-app-43ddd.firebaseapp.com',
    storageBucket: 'study-app-43ddd.firebasestorage.app',
  );
}
